#version: '3.1'

volumes:
  postgres:

services:
  app:
    build: .
    env_file: local.env
    ports:
        - "8100:8100"

  postgres:
    image: 'postgres:12-alpine'
    environment:
      - 'POSTGRES_DB=employees'
      - 'POSTGRES_USER=entropay'
      - 'POSTGRES_PASSWORD=entropay'
      - 'PGDATA=/var/lib/postgresql/data/employees'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data/employees'

  pgweb:
    image: 'sosedoff/pgweb:latest'
    depends_on:
      - 'postgres'
    environment:
      - 'DATABASE_URL=postgres://entropay:entropay@postgres:5432/employees?sslmode=disable'
      - 'VIRTUAL_HOST=pgweb'
      - 'VIRTUAL_PORT=8081'
    ports:
      - '8081:8081'
