-- Add technology_type column to technology table
ALTER TABLE technology ADD COLUMN IF NOT EXISTS technology_type VARCHAR(50);

delete from technology;

drop table employee_technology;

insert into technology (id, name, technology_type, created_at, modified_at, deleted)
values (gen_random_uuid(), '.NET', 'BACKEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Amazon RDS', 'DATABASE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Angular', 'FRONTEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'AWS (general)', 'CLOUD_INFRASTRUCTURE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Azure (general)', 'CLOUD_INFRASTRUCTURE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Basics of Scrum', 'AGILE_METHODOLOGY', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'C#', 'PROGRAMMING_LANGUAGE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'C++', 'PROGRAMMING_LANGUAGE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Cassandra', 'DATABASE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'CircleCI', 'CICD_DEVOPS', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'CSS', 'WEB_FUNDAMENTALS', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Cypress', 'TESTING_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Django', 'BACKEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Docker', 'CLOUD_INFRASTRUCTURE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'DynamoDB', 'DATABASE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Elasticsearch', 'DATABASE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Express.js', 'BACKEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'FastAPI', 'BACKEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Firebase Realtime Database', 'DATABASE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Flask', 'BACKEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'GCP (general)', 'CLOUD_INFRASTRUCTURE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'GitHub Actions', 'CICD_DEVOPS', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'GitLab CI/CD', 'CICD_DEVOPS', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Go', 'PROGRAMMING_LANGUAGE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'HTML', 'WEB_FUNDAMENTALS', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Hybrid (Scrum + Kanban)', 'AGILE_METHODOLOGY', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Java', 'PROGRAMMING_LANGUAGE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'JavaScript', 'PROGRAMMING_LANGUAGE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Jenkins', 'CICD_DEVOPS', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Jest', 'TESTING_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'JUnit', 'TESTING_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Kanban', 'AGILE_METHODOLOGY', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Kotlin', 'PROGRAMMING_LANGUAGE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Kubernetes', 'CLOUD_INFRASTRUCTURE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Laravel', 'BACKEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'MongoDB', 'DATABASE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'MySQL', 'DATABASE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'NestJS', 'BACKEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Next.js', 'FRONTEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Node.js', 'PROGRAMMING_LANGUAGE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'PHP', 'PROGRAMMING_LANGUAGE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'PostgreSQL', 'DATABASE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Python', 'PROGRAMMING_LANGUAGE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'React', 'FRONTEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Redis', 'DATABASE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Ruby', 'PROGRAMMING_LANGUAGE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Ruby on Rails', 'BACKEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Scrum', 'AGILE_METHODOLOGY', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Selenium', 'TESTING_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Spring / Spring Boot', 'BACKEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'SQL Server', 'DATABASE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'SQLite', 'DATABASE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Svelte', 'FRONTEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Symfony', 'BACKEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Terraform', 'CLOUD_INFRASTRUCTURE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'TypeScript', 'PROGRAMMING_LANGUAGE', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'Vue.js', 'FRONTEND_FRAMEWORK', current_timestamp, current_timestamp, false),
       (gen_random_uuid(), 'AI', 'AI', current_timestamp, current_timestamp, false);