-- Add skills permissions for ROLE_ADMIN
UPDATE public.config SET permissions = e'[
    {"entity": "employees", "actions": ["create", "read", "update", "delete"]},
    {"entity": "contracts", "actions": ["create", "read", "update", "delete"]},
    {"entity": "assignments", "actions": ["create", "read", "update", "delete"]},
    {"entity": "clients", "actions": ["create", "read", "update", "delete"]},
    {"entity": "companies", "actions": ["create", "read", "update", "delete"]},
    {"entity": "projects", "actions": ["create", "read", "update", "delete"]},
    {"entity": "project-types", "actions": ["create", "read", "update", "delete"]},
    {"entity": "roles", "actions": ["create", "read", "update", "delete"]},
    {"entity": "seniorities", "actions": ["create", "read", "update", "delete"]},
    {"entity": "technologies", "actions": ["create", "read", "update", "delete"]},
    {"entity": "tenants", "actions": ["create", "read", "update", "delete"]},
    {"entity": "leave-types", "actions": ["create", "read", "update", "delete"]},
    {"entity": "holidays", "actions": ["create", "read", "update", "delete"]},
    {"entity": "countries", "actions": ["create", "read", "update", "delete"]},
    {"entity": "vacations", "actions": ["create", "read", "update", "delete"]},
    {"entity": "ptos", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/employees", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/ptos/employees", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/salaries", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/billing", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/margin", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/turnover/flat", "actions": ["create", "read", "update", "delete"]},
    {"entity": "overtimes", "actions": ["create", "read", "update", "delete"]},
    {"entity": "feedback/employee", "actions": ["create", "read", "update", "delete"]},
    {"entity": "feedback/client", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reimbursement-categories", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reimbursements", "actions": ["create", "read", "update", "delete"]},
    {"entity": "skills", "actions": ["create", "read", "update", "delete"]},
    {"entity": "feedback-summary", "actions": ["create", "read", "update", "delete"]}
]' WHERE role = 'ROLE_ADMIN';

-- Add skills permissions for ROLE_MANAGER_HR
UPDATE public.config SET permissions = e'[
    {"entity": "employees", "actions": ["create", "read", "update"]},
    {"entity": "contracts", "actions": ["create", "read", "update", "delete"]},
    {"entity": "assignments", "actions": ["create", "read", "update", "delete"]},
    {"entity": "clients", "actions": ["create", "read", "update"]},
    {"entity": "companies", "actions": ["create", "read", "update", "delete"]},
    {"entity": "projects", "actions": ["create", "read", "update"]},
    {"entity": "project-types", "actions": ["create", "read", "update", "delete"]},
    {"entity": "roles", "actions": ["create", "read", "update", "delete"]},
    {"entity": "seniorities", "actions": ["create", "read", "update", "delete"]},
    {"entity": "technologies", "actions": ["create", "read", "update", "delete"]},
    {"entity": "end-reasons", "actions": ["create", "read", "update", "delete"]},
    {"entity": "tenants", "actions": ["create", "read", "update", "delete"]},
    {"entity": "leave-types", "actions": ["create", "read", "update", "delete"]},
    {"entity": "holidays", "actions": ["create", "read", "update", "delete"]},
    {"entity": "countries", "actions": ["create", "read", "update", "delete"]},
    {"entity": "vacations", "actions": ["create", "read", "update", "delete"]},
    {"entity": "ptos", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/employees", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/ptos/employees", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/salaries", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/billing", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/margin", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reports/turnover/flat", "actions": ["create", "read", "update", "delete"]},
    {"entity": "overtimes", "actions": ["create", "read", "update", "delete"]},
    {"entity": "feedback/employee", "actions": ["create", "read", "update", "delete"]},
    {"entity": "feedback/client", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reimbursement-categories", "actions": ["create", "read", "update", "delete"]},
    {"entity": "reimbursements", "actions": ["create", "read", "update", "delete"]},
    {"entity": "skills", "actions": ["create", "read", "update", "delete"]},
    {"entity": "feedback-summary", "actions": ["create", "read", "update", "delete"]}
]' WHERE role = 'ROLE_MANAGER_HR';
