name: Run build

on:
  pull_request


permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: development
    services:
      postgres:
        image: 'postgres:10.2-alpine'
        environment:
          - 'POSTGRES_DB=employees'
          - 'POSTGRES_USER=entropay'
          - 'POSTGRES_PASSWORD=entropay'
          - 'PGDATA=/var/lib/postgresql/data/employees'
        ports:
          - '5432:5432'
        volumes:
          - 'postgres:/var/lib/postgresql/data/employees'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Run build
      run: |
        mvn package
        mvn flyway:migrate
