name: Deploy to prod

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: entropay-employees
  ECS_SERVICE: entropay-employees
  ECS_CLUSTER: entropay-prod
  ECS_TASK_DEFINITION: .aws/task-definition.json
  CONTAINER_NAME: entropay-employees           

permissions:
  contents: read

jobs:
  tag:
    name: Tag
    runs-on: ubuntu-latest
    environment: production
    outputs:
      new-version: ${{ steps.set-version.outputs.new-version }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Get tag version
      run: |
        NEW_VERSION=${GITHUB_REF#refs/tags/}
        mvn versions:set -DnewVersion=$NEW_VERSION

    - name: Set Version
      id: set-version
      run: |
        export NEW_VERSION=$(mvn help:evaluate -Dexpression=project.version -Dexpression=project.version -q -DforceStdout)
        echo "::set-output name=new-version::${NEW_VERSION}"

  package-build-deploy:
    name: Package, build and deploy
    needs: tag
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        NEW_VERSION: ${{ needs.tag.outputs.new-version }}
      run: |
        # Build a docker container and push it to ECR so that it can be deployed to ECS.
        docker build . -t $ECR_REGISTRY/$ECR_REPOSITORY:NEW_VERSION
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:NEW_VERSION
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:NEW_VERSION"

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ env.ECS_TASK_DEFINITION }}
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true

  prepare-next-version:
    name: Prepare the next development version
    needs: tag
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set next version
        id: set-next-version
        run: |
          mvn versions:set -DnextSnapshot
          echo "next-version=$(mvn help:evaluate -Dexpression=project.version -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Create pull request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Prepare next dev version
          branch: next-version-${{ steps.set-next-version.outputs.next-version }}
          delete-branch: true
          title: 'Prepare next dev version'
          body: |
            Prepare next dev version
            - Updated pom to the next dev version
            - Auto-generated by [create-pull-request]

          draft: false
